from flask import Flask, request, jsonify
from flask_cors import CORS
import pandas as pd
import joblib

# Initialize Flask App
app = Flask(__name__)
# This is crucial to allow your React app (running on localhost:3000)
# to make requests to this server (running on localhost:5000)
CORS(app)

# Load the trained model
try:
    model = joblib.load("sales_cycle_model.pkl")
    print("✅ Model loaded successfully.")
except FileNotFoundError:
    print("❌ Model file not found! Make sure 'sales_cycle_model.pkl' is in the backend directory.")
    model = None

@app.route('/')
def home():
    return "<h1>Inexlink ML Model API</h1><p>The server is running. Use the /api endpoints to interact.</p>"

# Endpoint 1: For the interactive prediction tool
@app.route('/api/predict', methods=['POST'])
def predict():
    if model is None:
        return jsonify({'error': 'Model is not loaded'}), 500

    try:
        data = request.get_json(force=True)
        # The model expects a DataFrame, so we convert the incoming JSON
        equipment_df = pd.DataFrame([data])
        
        prediction = model.predict(equipment_df)
        predicted_days = round(prediction[0], 1)
        
        # Create a simple confidence interval
        lower_bound = round(predicted_days * 0.8, 1)
        upper_bound = round(predicted_days * 1.2, 1)

        result = {
            'estimated_days_to_sale': predicted_days,
            'confidence_interval': [lower_bound, upper_bound]
        }
        return jsonify(result)

    except Exception as e:
        return jsonify({'error': f"An error occurred during prediction: {str(e)}"}), 400


# Endpoint 2: To provide all aggregated data for the dashboard
@app.route('/api/dashboard_data', methods=['GET'])
def get_dashboard_data():
    # In a real-world scenario, this data would be generated by querying a database
    # and running aggregations. For this project, we return the data structure
    # the frontend expects, based on our ML model's known performance.
    
    dashboard_data = {
        "kpis": {
            "totalRevenue": 28750000, "avgListingPrice": 143750, "totalListings": 2000,
            "activeListings": 400, "avgTimeToSale": 26,
        },
        "equipmentPerformance": [
            { "name": 'Excavator', "sales": 500, "avgPrice": 280000, "revenue": 14000000 },
            { "name": 'Dump Truck', "sales": 400, "avgPrice": 150000, "revenue": 6000000 },
            { "name": 'Bulldozer', "sales": 300, "avgPrice": 95000, "revenue": 2850000 },
            { "name": 'Wheel Loader', "sales": 300, "avgPrice": 85000, "revenue": 2550000 },
            { "name": 'Crusher', "sales": 250, "avgPrice": 120000, "revenue": 3000000 },
            { "name": 'Conveyor System', "sales": 250, "avgPrice": 15000, "revenue": 375000 },
        ],
        "monthlyTrends": [
            { "month": 'Jan', "sales": 250, "listings": 300 }, { "month": 'Feb', "sales": 280, "listings": 320 },
            { "month": 'Mar', "sales": 350, "listings": 400 }, { "month": 'Apr', "sales": 400, "listings": 450 },
            { "month": 'May', "sales": 320, "listings": 380 }, { "month": 'Jun', "sales": 400, "listings": 450 },
        ],
        "regionalData": [
            { "region": 'W. Australia', "sales": 600, "revenue": 10200000 }, { "region": 'Queensland', "sales": 450, "revenue": 7650000 },
            { "region": 'Nevada USA', "sales": 350, "revenue": 5950000 }, { "region": 'Chile', "sales": 300, "revenue": 5100000 },
            { "region": 'South Africa', "sales": 300, "revenue": 5100000 },
        ],
        "sellerTypePerformance": [
            { "type": 'Mining Company', "avgTimeToSale": 22, "avgPrice": 165000 },
            { "type": 'Equipment Dealer', "avgTimeToSale": 19, "avgPrice": 130000 },
            { "type": 'Rental Company', "avgTimeToSale": 31, "avgPrice": 125000 },
            { "type": 'Construction Co.', "avgTimeToSale": 35, "avgPrice": 115000 },
        ],
        "modelPerformance": { "rSquared": 0.524, "mae": 6.3, "rmse": 8.5 },
        "predictiveInsights": [
            { "id": 'EX-001', "equipment": 'Excavator', "listingPrice": 280000, "estimatedDays": 26.9, "confidence": [21.6, 32.3] },
            { "id": 'DT-002', "equipment": 'Dump Truck', "listingPrice": 65000, "estimatedDays": 45.1, "confidence": [38.2, 53.0] },
            { "id": 'BD-003', "equipment": 'Bulldozer', "listingPrice": 150000, "estimatedDays": 14.5, "confidence": [11.1, 18.9] },
            { "id": 'CR-004', "equipment": 'Crusher', "listingPrice": 90000, "estimatedDays": 88.7, "confidence": [75.0, 102.4] },
        ],
        "featureImportance": [
            { "feature": 'Equipment Age (Years)', "importance": 0.2343 }, { "feature": 'Listing Price', "importance": 0.1311 },
            { "feature": 'Original Value', "importance": 0.1301 }, { "feature": 'Hours Per Year', "importance": 0.0621 },
            { "feature": 'Price to Original Ratio', "importance": 0.0514 }, { "feature": 'Operating Hours', "importance": 0.0484 },
            { "feature": 'Condition (Needs Repair)', "importance": 0.0316 }, { "feature": 'Has Warranty', "importance": 0.0355 },
        ]
    }
    return jsonify(dashboard_data)

if __name__ == '__main__':
    app.run(port=5000, debug=True)