"""
Inexlink ML Model API — Sprint 6 Refactor
Task 3.1: Flask API refactoring for dynamic model swapping

Changes from Phase 1:
- Models loaded lazily and cached at runtime (no restart needed to switch)
- /api/predict now accepts optional `model_name` param: ridge | random_forest | xgboost
- /api/models endpoint lists available models and their benchmark metrics
- /api/health endpoint for monitoring
- /api/feature_importance endpoint — live from trained model, not hardcoded
- /api/predictive_insights endpoint — live predictions for sample listings
- Consistent error response shape across all endpoints
- Metrics loaded dynamically from models/metrics.json (generated by training notebook)
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import pandas as pd
import joblib
import json
import os
import numpy as np

app = Flask(__name__)
CORS(app)

# ── Model registry ─────────────────────────────────────────────────────────────
MODEL_REGISTRY = {
    "ridge": {
        "path": "models/ridge_model.pkl",
        "display_name": "Ridge Regression",
        "phase": "Phase 1 baseline",
    },
    "random_forest": {
        "path": "models/random_forest_model.pkl",
        "display_name": "Random Forest (Tuned)",
        "phase": "Sprint 6",
    },
    "xgboost": {
        "path": "models/xgboost_model.pkl",
        "display_name": "XGBoost (Tuned)",
        "phase": "Sprint 6",
    },
}

DEFAULT_MODEL = "ridge"

# ── Human-readable feature name mapping ───────────────────────────────────────
FEATURE_NAME_MAP = {
    'age_years':                        'Equipment Age (Years)',
    'listing_price':                    'Listing Price',
    'original_value':                   'Original Value',
    'hours_per_year':                   'Hours Per Year',
    'price_to_original_ratio':          'Price to Original Ratio',
    'operating_hours':                  'Operating Hours',
    'photos_count':                     'Photo Count',
    'description_length':               'Description Length',
    'listing_month':                    'Listing Month',
    'has_maintenance_records':          'Has Maintenance Records',
    'has_warranty':                     'Has Warranty',
    'condition_Needs Repair':           'Condition: Needs Repair',
    'condition_Good':                   'Condition: Good',
    'condition_Fair':                   'Condition: Fair',
    'condition_Excellent':              'Condition: Excellent',
    'equipment_type_Dump Truck':        'Type: Dump Truck',
    'equipment_type_Excavator':         'Type: Excavator',
    'equipment_type_Bulldozer':         'Type: Bulldozer',
    'equipment_type_Wheel Loader':      'Type: Wheel Loader',
    'equipment_type_Crusher':           'Type: Crusher',
    'equipment_type_Conveyor System':   'Type: Conveyor System',
    'manufacturer_Caterpillar':         'Manufacturer: Caterpillar',
    'manufacturer_Komatsu':             'Manufacturer: Komatsu',
    'manufacturer_Liebherr':            'Manufacturer: Liebherr',
    'manufacturer_Volvo':               'Manufacturer: Volvo',
    'manufacturer_Hitachi':             'Manufacturer: Hitachi',
    'manufacturer_JCB':                 'Manufacturer: JCB',
    'seller_type_Equipment Dealer':     'Seller: Equipment Dealer',
    'seller_type_Mining Company':       'Seller: Mining Company',
    'seller_type_Rental Company':       'Seller: Rental Company',
    'seller_type_Construction Company': 'Seller: Construction Co.',
    'location_Queensland':              'Location: Queensland',
    'location_Western Australia':       'Location: W. Australia',
    'location_New South Wales':         'Location: NSW',
    'location_Alberta Canada':          'Location: Alberta',
    'location_Nevada USA':              'Location: Nevada',
    'location_Chile':                   'Location: Chile',
    'location_South Africa':            'Location: South Africa',
}


def clean_feature_name(raw: str) -> str:
    """Strip sklearn prefixes and apply human-readable mapping."""
    stripped = raw.replace("num__", "").replace("cat__", "").replace("bin__", "")
    if stripped in FEATURE_NAME_MAP:
        return FEATURE_NAME_MAP[stripped]
    # Fallback: replace underscores and title-case
    return stripped.replace("_", " ").title()


# ── Load metrics from file generated by training notebook ──────────────────────
_metrics = {}
try:
    with open("models/metrics.json") as f:
        _metrics = json.load(f)
    print("✅ Metrics loaded from models/metrics.json")
    for key, m in _metrics.items():
        print(f"   {key}: MAE={m['mae']} | RMSE={m['rmse']} | R²={m['r2']}")
except FileNotFoundError:
    print("⚠️  models/metrics.json not found — run the training notebook first")

# Runtime cache — models loaded on first request, kept in memory
_model_cache: dict = {}

# Sample listings used for the predictive insights table
SAMPLE_LISTINGS = [
    {"id": "EX-001", "equipment": "Excavator",  "equipment_type": "Excavator",  "manufacturer": "Caterpillar", "condition": "Good",         "age_years": 5.0,  "listing_price": 280000, "operating_hours": 8000,  "original_value": 450000, "location": "Western Australia", "seller_type": "Mining Company",   "has_maintenance_records": True,  "has_warranty": False, "photos_count": 12, "description_length": 300, "listing_month": 6, "price_to_original_ratio": 0.62, "hours_per_year": 1600},
    {"id": "DT-002", "equipment": "Dump Truck", "equipment_type": "Dump Truck", "manufacturer": "Komatsu",     "condition": "Fair",         "age_years": 10.0, "listing_price": 65000,  "operating_hours": 25000, "original_value": 380000, "location": "Queensland",        "seller_type": "Rental Company",   "has_maintenance_records": False, "has_warranty": False, "photos_count": 5,  "description_length": 150, "listing_month": 3, "price_to_original_ratio": 0.17, "hours_per_year": 2500},
    {"id": "BD-003", "equipment": "Bulldozer",  "equipment_type": "Bulldozer",  "manufacturer": "Caterpillar", "condition": "Excellent",    "age_years": 2.0,  "listing_price": 150000, "operating_hours": 2000,  "original_value": 520000, "location": "Nevada USA",        "seller_type": "Equipment Dealer", "has_maintenance_records": True,  "has_warranty": True,  "photos_count": 15, "description_length": 450, "listing_month": 9, "price_to_original_ratio": 0.29, "hours_per_year": 1000},
    {"id": "CR-004", "equipment": "Crusher",    "equipment_type": "Crusher",    "manufacturer": "Liebherr",    "condition": "Needs Repair", "age_years": 12.0, "listing_price": 90000,  "operating_hours": 48000, "original_value": 800000, "location": "Chile",             "seller_type": "Mining Company",   "has_maintenance_records": False, "has_warranty": False, "photos_count": 3,  "description_length": 100, "listing_month": 1, "price_to_original_ratio": 0.11, "hours_per_year": 4000},
]

PREDICTION_FEATURES = [
    "equipment_type", "manufacturer", "condition", "age_years", "listing_price",
    "operating_hours", "original_value", "location", "seller_type",
    "has_maintenance_records", "has_warranty", "photos_count",
    "description_length", "listing_month", "price_to_original_ratio", "hours_per_year",
]


def load_model(model_name: str):
    """Load model from disk into cache. Returns pipeline or raises."""
    if model_name not in MODEL_REGISTRY:
        raise ValueError(f"Unknown model '{model_name}'. Available: {list(MODEL_REGISTRY.keys())}")
    if model_name not in _model_cache:
        path = MODEL_REGISTRY[model_name]["path"]
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Model file not found: '{path}'. "
                "Run Sprint6_Model_Benchmarking.ipynb to generate model files."
            )
        _model_cache[model_name] = joblib.load(path)
        print(f"✅ Loaded '{model_name}' from {path}")
    return _model_cache[model_name]


def error_response(message: str, status: int = 400):
    return jsonify({"success": False, "error": message}), status


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.route("/")
def home():
    return """
    <h1>Inexlink ML API — Sprint 6</h1>
    <ul>
      <li><code>GET  /api/health</code> — service health check</li>
      <li><code>GET  /api/models</code> — list available models and metrics</li>
      <li><code>POST /api/predict</code> — predict days to sale</li>
      <li><code>GET  /api/feature_importance</code> — live feature importance from model</li>
      <li><code>GET  /api/predictive_insights</code> — live predictions for sample listings</li>
      <li><code>GET  /api/dashboard_data</code> — aggregated KPI data</li>
    </ul>
    """


@app.route("/api/health")
def health():
    return jsonify({
        "success": True,
        "status": "ok",
        "loaded_models": list(_model_cache.keys()),
        "available_models": list(MODEL_REGISTRY.keys()),
        "default_model": DEFAULT_MODEL,
        "metrics_loaded": bool(_metrics),
    })


@app.route("/api/models")
def list_models():
    models_info = {}
    for key, meta in MODEL_REGISTRY.items():
        models_info[key] = {
            "display_name": meta["display_name"],
            "phase": meta["phase"],
            "metrics": _metrics.get(key, {}),
            "loaded": key in _model_cache,
            "is_default": key == DEFAULT_MODEL,
        }
    return jsonify({"success": True, "models": models_info})


@app.route("/api/feature_importance")
def feature_importance():
    """
    Live feature importance extracted directly from the trained model.
    Tree-based models use feature_importances_, Ridge uses abs(coef_).

    Optional query params:
        model_name: ridge | random_forest | xgboost  (default: xgboost)
        top_n: number of top features to return (default: 10)
    """
    model_name = request.args.get("model_name", DEFAULT_MODEL).strip().lower()
    top_n = int(request.args.get("top_n", 10))

    try:
        pipeline = load_model(model_name)
    except (ValueError, FileNotFoundError) as e:
        return error_response(str(e), 500)

    try:
        preprocessor = pipeline.named_steps["pre"]
        regressor    = pipeline.named_steps["reg"]
        feature_names = preprocessor.get_feature_names_out()

        if hasattr(regressor, "feature_importances_"):
            importances = regressor.feature_importances_
        elif hasattr(regressor, "coef_"):
            importances = np.abs(regressor.coef_)
        else:
            return error_response(f"Model '{model_name}' does not expose feature importances.", 400)

        clean_names = [clean_feature_name(str(n)) for n in feature_names]

        pairs = sorted(
            zip(clean_names, importances.tolist()),
            key=lambda x: x[1],
            reverse=True
        )[:top_n]

        result = [{"feature": name, "importance": round(imp, 4)} for name, imp in pairs]

        return jsonify({
            "success": True,
            "model_used": model_name,
            "model_display_name": MODEL_REGISTRY[model_name]["display_name"],
            "feature_importance": result,
        })

    except Exception as e:
        return error_response(f"Failed to extract feature importance: {str(e)}", 500)


@app.route("/api/predictive_insights")
def predictive_insights():
    """
    Run live predictions on sample listings using the active model.
    Replaces the hardcoded predictive insights table in the dashboard.

    Optional query param:
        model_name: ridge | random_forest | xgboost  (default: xgboost)
    """
    model_name = request.args.get("model_name", DEFAULT_MODEL).strip().lower()

    try:
        pipeline = load_model(model_name)
    except (ValueError, FileNotFoundError) as e:
        return error_response(str(e), 500)

    try:
        results = []
        for listing in SAMPLE_LISTINGS:
            df = pd.DataFrame([{k: listing[k] for k in PREDICTION_FEATURES}])
            predicted_days = max(0.1, round(float(pipeline.predict(df)[0]), 1))
            results.append({
                "id":            listing["id"],
                "equipment":     listing["equipment"],
                "listingPrice":  listing["listing_price"],
                "estimatedDays": predicted_days,
                "confidence":    [round(predicted_days * 0.8, 1), round(predicted_days * 1.2, 1)],
            })

        return jsonify({
            "success": True,
            "model_used": model_name,
            "model_display_name": MODEL_REGISTRY[model_name]["display_name"],
            "insights": results,
        })

    except Exception as e:
        return error_response(f"Failed to generate insights: {str(e)}", 500)


@app.route("/api/predict", methods=["POST"])
def predict():
    """
    Predict days to sale for a mining equipment listing.
    Optional query param: model_name (default: xgboost)
    """
    model_name = request.args.get("model_name", DEFAULT_MODEL).strip().lower()

    try:
        pipeline = load_model(model_name)
    except ValueError as e:
        return error_response(str(e), 400)
    except FileNotFoundError as e:
        return error_response(str(e), 500)

    data = request.get_json(force=True, silent=True)
    if not data:
        return error_response("Request body must be valid JSON.", 400)

    missing = [f for f in PREDICTION_FEATURES if f not in data]
    if missing:
        return error_response(f"Missing required fields: {missing}", 400)

    try:
        df = pd.DataFrame([data])
        predicted_days = round(float(pipeline.predict(df)[0]), 1)
        return jsonify({
            "success": True,
            "model_used": model_name,
            "model_display_name": MODEL_REGISTRY[model_name]["display_name"],
            "estimated_days_to_sale": predicted_days,
            "estimated_weeks": round(predicted_days / 7, 1),
            "confidence_interval": [
                round(predicted_days * 0.8, 1),
                round(predicted_days * 1.2, 1),
            ],
        })
    except Exception as e:
        return error_response(f"Prediction failed: {str(e)}", 500)


@app.route("/api/dashboard_data")
def dashboard_data():
    """Aggregated KPI and analytics data for the React dashboard."""
    data = {
        "kpis": {
            "totalRevenue": 28_750_000,
            "avgListingPrice": 143_750,
            "totalListings": 2000,
            "activeListings": 400,
            "avgTimeToSale": 26,
        },
        "equipmentPerformance": [
            {"name": "Excavator",       "sales": 500, "avgPrice": 280_000, "revenue": 14_000_000},
            {"name": "Dump Truck",      "sales": 400, "avgPrice": 150_000, "revenue":  6_000_000},
            {"name": "Bulldozer",       "sales": 300, "avgPrice":  95_000, "revenue":  2_850_000},
            {"name": "Wheel Loader",    "sales": 300, "avgPrice":  85_000, "revenue":  2_550_000},
            {"name": "Crusher",         "sales": 250, "avgPrice": 120_000, "revenue":  3_000_000},
            {"name": "Conveyor System", "sales": 250, "avgPrice":  15_000, "revenue":    375_000},
        ],
        "monthlyTrends": [
            {"month": "Jan", "sales": 250, "listings": 300},
            {"month": "Feb", "sales": 280, "listings": 320},
            {"month": "Mar", "sales": 350, "listings": 400},
            {"month": "Apr", "sales": 400, "listings": 450},
            {"month": "May", "sales": 320, "listings": 380},
            {"month": "Jun", "sales": 400, "listings": 450},
        ],
        "regionalData": [
            {"region": "W. Australia", "sales": 600, "revenue": 10_200_000},
            {"region": "Queensland",   "sales": 450, "revenue":  7_650_000},
            {"region": "Nevada USA",   "sales": 350, "revenue":  5_950_000},
            {"region": "Chile",        "sales": 300, "revenue":  5_100_000},
            {"region": "South Africa", "sales": 300, "revenue":  5_100_000},
        ],
        "sellerTypePerformance": [
            {"type": "Mining Company",   "avgTimeToSale": 22, "avgPrice": 165_000},
            {"type": "Equipment Dealer", "avgTimeToSale": 19, "avgPrice": 130_000},
            {"type": "Rental Company",   "avgTimeToSale": 31, "avgPrice": 125_000},
            {"type": "Construction Co.", "avgTimeToSale": 35, "avgPrice": 115_000},
        ],
        "modelPerformance": {
            key: {
                "rSquared": _metrics.get(key, {}).get("r2"),
                "mae":      _metrics.get(key, {}).get("mae"),
                "rmse":     _metrics.get(key, {}).get("rmse"),
                "cvR2":     _metrics.get(key, {}).get("cv_r2_mean"),
                "label":    MODEL_REGISTRY[key]["display_name"],
            }
            for key in MODEL_REGISTRY
        },
    }
    return jsonify(data)


if __name__ == "__main__":
    print("🚀 Inexlink API — Sprint 6")
    print(f"   Default model : {DEFAULT_MODEL}")
    print(f"   Available     : {list(MODEL_REGISTRY.keys())}")
    print("   Switch models via ?model_name=ridge | random_forest | xgboost")
    app.run(port=5000, debug=True)